apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads
  labels:
    {{- include "smartintern.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.backend.uploads.storageClass }}
  storageClassName: {{ .Values.backend.uploads.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.uploads.size }}
