apiVersion: v1
kind: Service
metadata:
  name: smartintern-ingress-metrics
  namespace: ingress-nginx
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "10254"
  labels:
    app.kubernetes.io/name: smartintern-ingress-metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: metrics
      port: 10254
      targetPort: 10254
