sonar.projectKey=smartintern-ai
sonar.projectName=SmartIntern AI
sonar.sourceEncoding=UTF-8

sonar.sources=frontend-web/src,backend-api/src,ai-service/app,mobile-app/src
sonar.tests=frontend-web/tests,backend-api/tests,ai-service/tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.expo/**,**/.venv/**,**/__pycache__/**,**/*.generated.*
sonar.test.inclusions=frontend-web/tests/**,backend-api/tests/**,ai-service/tests/**

sonar.javascript.lcov.reportPaths=frontend-web/coverage/lcov.info,backend-api/coverage/lcov.info
sonar.python.coverage.reportPaths=ai-service/coverage.xml
sonar.python.version=3.11
sonar.javascript.node.maxspace=512
