import { LinearGradient } from 'expo-linear-gradient';
import { StyleSheet, Text, View } from 'react-native';
import { useAppTheme } from '@/core/theme/ThemeProvider';
import type { AppTheme } from '@/core/theme/theme';
import type { AiMatchResult } from '../models/aiMatchResult';

const decisionLabels: Record<string, string> = { STRONG_MATCH: 'Compatibilite forte', GOOD_MATCH: 'Bonne compatibilite', PARTIAL_MATCH: 'Compatibilite partielle', LOW_MATCH: 'Compatibilite limitee', VERY_LOW_MATCH: 'Compatibilite tres limitee', INSUFFICIENT_DATA: 'Donnees insuffisantes' };
const confidenceLabels: Record<string, string> = { HIGH: 'Confiance elevee', MEDIUM: 'Confiance moyenne', LOW: 'Confiance faible' };

export function AiMatchScoreCard({ analysis, analyzedAt }: { analysis: AiMatchResult; analyzedAt?: string }) {
  const { theme } = useAppTheme(); const styles = createStyles(theme);
  return <LinearGradient colors={theme.gradients.premium} style={styles.card}><View style={styles.scoreCircle}>{analysis.score === undefined ? <Text style={styles.noScore}>N/A</Text> : <><Text accessibilityLabel={`Score de compatibilite ${Math.round(analysis.score)} sur 100`} style={styles.score}>{Math.round(analysis.score)}</Text><Text style={styles.unit}>/100</Text></>}</View><View style={styles.copy}><Text style={styles.eyebrow}>MATCHING V3</Text><Text style={styles.title}>{analysis.decisionLabel ? decisionLabels[analysis.decisionLabel] ?? analysis.decisionLabel : 'Verdict non disponible'}</Text><Text style={styles.confidence}>{analysis.confidence ? confidenceLabels[analysis.confidence] ?? analysis.confidence : 'Confiance non disponible'}</Text>{analyzedAt ? <Text style={styles.date}>Analyse lancee le {new Intl.DateTimeFormat('fr-FR', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(analyzedAt))}</Text> : null}</View>{analysis.explanation ? <Text style={styles.explanation}>{analysis.explanation}</Text> : null}</LinearGradient>;
}
const createStyles = (theme: AppTheme) => StyleSheet.create({ card: { borderRadius: theme.radius.xl, padding: theme.spacing.xl, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: theme.spacing.lg, ...theme.shadow }, scoreCircle: { width: 88, height: 88, borderRadius: 44, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.12)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)' }, score: { color: theme.colors.white, fontSize: 34, lineHeight: 38, fontWeight: '800' }, noScore: { color: theme.colors.white, ...theme.typography.heading }, unit: { color: 'rgba(255,255,255,0.68)', ...theme.typography.caption }, copy: { flex: 1, minWidth: 190, gap: theme.spacing.xs }, eyebrow: { color: '#A7F3D0', ...theme.typography.overline }, title: { color: theme.colors.white, ...theme.typography.heading }, confidence: { color: 'rgba(255,255,255,0.8)', ...theme.typography.caption }, date: { color: 'rgba(255,255,255,0.58)', ...theme.typography.caption }, explanation: { width: '100%', color: 'rgba(255,255,255,0.78)', ...theme.typography.body } });
