apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartintern
resources:
  - ../../../base/migrations
images:
  - name: bessem785/smartintern-backend-migrate
    newTag: IMAGE_TAG_PLACEHOLDER
